version: "3.3"
services:
  postgres-inventory-control:
    image: postgres:latest
    container_name: postgres-inventory-control
    restart: always
    environment:
      POSTGRES_DB: inventory_control
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    networks:
      - inventory-control-network
  app:
    restart: always
    build: .
    working_dir: /api
    environment:
      SPRING_PROFILES_ACTIVE prod
    volumes: 
      - .:/api
      - ~/.m2:/root/m2
    ports:
      - "8085:8085"
    command: mvn clean spring-boot:run
    depends_on:
      - postgres-inventory-control
    links:
      - postgres-inventory-control
    networks:
      - inventory-control-network
networks:
  inventory-control-network:
        driver: bridge
